# Generated by Django 5.0.2 on 2024-03-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_fine_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine_tickets',
            old_name='provisin',
            new_name='provision',
        ),
    ]
