# Generated by Django 5.0.3 on 2024-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_rename_provisin_fine_tickets_provision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.IntegerField()),
                ('reference_no', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_address', models.TextField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
