# Generated by Django 5.0.3 on 2024-03-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_add_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_vehicle',
        ),
    ]
