# Generated by Django 5.0.3 on 2024-03-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='reference_no',
        ),
    ]
