# Generated by Django 5.0.3 on 2024-03-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtd', '0002_remove_add_vehicle_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_no',
            field=models.CharField(max_length=20),
        ),
    ]
