# Generated by Django 5.0.3 on 2024-04-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtd', '0003_alter_add_vehicle_vehicle_no'),
        ('user', '0002_driver_registration_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='license_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.driver_registration'),
            preserve_default=False,
        ),
    ]
