# Generated by Django 5.0.3 on 2024-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.IntegerField()),
                ('police_id', models.CharField(max_length=20)),
                ('license_id', models.CharField(max_length=20)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('class_of_vehicle', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=255)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('issued_time', models.TimeField()),
                ('expired_date', models.DateField(auto_now=True)),
                ('court_date', models.DateField(auto_now=True)),
                ('provision', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('paid_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
