# Generated by Django 5.0.3 on 2024-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuefine',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
