# Generated by Django 5.0.3 on 2024-04-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_driver_registration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_type', models.CharField(max_length=255)),
                ('accident_desc', models.TextField()),
                ('accident_loc', models.CharField(max_length=255)),
                ('accident_date', models.DateField(auto_now=True)),
                ('accident_time', models.TimeField()),
                ('accident_image', models.ImageField(upload_to='report/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driver_registration')),
            ],
        ),
    ]
